name: Compile examples

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '30 3 * * 5' # Run every Friday at 3:30 AM UTC
    # adding useless change to trigger the workflow 1
    
jobs:
  arduino-devops:
    uses: Infineon/arduino-devops/.github/workflows/compile-examples.yml@core-install-from-local