name: Release

on:
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: ''
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  arduino-devops:
    uses: Infineon/arduino-devops/.github/workflows/release.yml@enable-bypass-rule
    with:
      version: ${{ inputs.version }}
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Is secret available?
      id: check_secret
      run: |
        if [[ -z "${{ secrets.RELEASE_WFLOW_SSH_KEY }}" ]]; then
          echo "SSH key is not available. Skipping release workflow."
          exit 1
        else
          echo "SSH key is available."
        fi